#include <catch2/catch_test_macros.hpp>

#ifdef SAXFX_HAS_ONNX

#include "dsp/OnnxInference.h"
#include <cmath>
#include <vector>

// Path to the identity model generated by scripts/generate_identity_model.py
// CTest runs from the build directory; model is at ../tests/models/identity.onnx
static const char* kIdentityModelPath =
#ifdef IDENTITY_MODEL_PATH
    IDENTITY_MODEL_PATH;
#else
    "../tests/models/identity.onnx";
#endif

TEST_CASE("OnnxInference -- loads identity model", "[onnx]")
{
    dsp::OnnxInference model(kIdentityModelPath);
    REQUIRE(model.isLoaded());
}

TEST_CASE("OnnxInference -- identity model output equals input", "[onnx]")
{
    dsp::OnnxInference model(kIdentityModelPath);

    // Create input: 512 samples of a ramp
    std::vector<float> input(512);
    for (int i = 0; i < 512; ++i)
        input[static_cast<size_t>(i)] = static_cast<float>(i) / 512.0f;

    auto output = model.run(input);

    REQUIRE(output.size() == input.size());

    // Verify output == input (identity model)
    for (size_t i = 0; i < input.size(); ++i)
        REQUIRE(output[i] == input[i]);
}

TEST_CASE("OnnxInference -- identity model preserves sine wave", "[onnx]")
{
    dsp::OnnxInference model(kIdentityModelPath);

    // Create a sine wave input
    std::vector<float> input(512);
    const float freq = 440.0f;
    const float sr   = 44100.0f;
    for (int i = 0; i < 512; ++i)
        input[static_cast<size_t>(i)] = 0.8f * std::sin(
            2.0f * 3.14159265f * freq * static_cast<float>(i) / sr);

    auto output = model.run(input);

    REQUIRE(output.size() == 512);
    for (size_t i = 0; i < 512; ++i)
        REQUIRE(output[i] == input[i]);
}

TEST_CASE("OnnxInference -- inputSize returns 512 for identity model", "[onnx]")
{
    dsp::OnnxInference model(kIdentityModelPath);
    REQUIRE(model.inputSize() == 512);
}

TEST_CASE("OnnxInference -- invalid path throws", "[onnx]")
{
    REQUIRE_THROWS_AS(
        dsp::OnnxInference("nonexistent_model.onnx"),
        Ort::Exception);
}

#else // !SAXFX_HAS_ONNX

TEST_CASE("OnnxInference -- skipped (ONNX Runtime not enabled)", "[onnx]")
{
    SUCCEED("ONNX Runtime not available — test skipped");
}

#endif // SAXFX_HAS_ONNX
