name: PingPongDelay CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure MSVC
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Configure and Build (Windows)
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DJUCE_ASIO_SDK_PATH=third_party/ASIO
          cmake --build build --config Release --parallel
      - name: Run Tests (Windows)
        run: |
          cmake --build build --config Release --target SaxFXTests --parallel
          ./build/tests/Release/SaxFXTests.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
      - name: Configure
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cmake --build build --config Release --parallel
      - name: Run tests
        run: |
          cmake --build build --config Release --target SaxFXTests --parallel
          ./build/tests/Release/SaxFXTests.exe
